version: "3"

services:
  mariadb:
    image: mariadb:11.4
    volumes:
      - mariadb-only-vol:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
     - MYSQL_DATABASE=fredbetdb
     - MYSQL_ROOT_PASSWORD=secred
     - MYSQL_USER=fred
     - MYSQL_PASSWORD=fred
volumes:
  mariadb-only-vol:
